os:
  - linux
language: node_js
node_js:
  - '12'
dist: xenial
sudo: required
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
install:
  - npm set progress=false
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages
  - npm install codecov -g
  - npm install
script:
  - npm test --verbose
  - codecov
  - ng build --prod --base-href "https://phptuts.github.io/ElectroBlocks/"