export enum ElectricComponentType {
	SERVO = 'SERVO',
	EMPTY = 'EMPTY',
	LCD_SCREEN = 'LCD_SCREEN',
	LED_MATRIX = 'LED_MATRIX',
	NEO_PIXEL_STRIP = 'NEO_PIXEL_STRIP',
	MOTOR = 'MOTOR',
	PIN = 'PIN',
	ARDUINO = 'ARDUINO',
	BLUE_TOOTH = 'BLUE_TOOTH',
	LED_COLOR = 'LED_COLOR'
}
