
export enum ActionType {
	EMPTY = 'EMPTY',

	DELAY = 'DELAY',

	SERVO_MOVE = 'SERVO_MOVE',

	ANALOG_PIN_WRITE = 'ANALOG_PIN_WRITE',
	DIGITAL_PIN_WRITE = 'DIGITAL_PIN_WRITE',


	LED_MATRIX_DRAW = 'LED_MATRIX_DRAW',

	LCD_SCREEN_PRINT = 'LCD_SCREEN_PRINT',
	LCD_SCREEN_BLINK = 'LCD_SCREEN_BLINK',
	LCD_SCREEN_BACK_LIGHT = 'LCD_SCREEN_BACK_LIGHT',
	LCD_SCREEN_CLEAR = 'LCD_SCREEN_CLEAR',

	BLUE_TOOTH_SEND_MESSAGE = 'BLUE_TOOTH_SEND_MESSAGE',

	NEO_PIXEL_LIGHT_UP = 'NEO_PIXEL_LIGHT_UP',

	ARDUINO_SEND_MESSAGE = 'ARDUINO_SEND_MESSAGE',

	MOTOR_MOVE = 'MOTOR_MOVE'
}
