export enum ElectricComponentType {
  SERVO = 'SERVO',
  EMPTY = 'EMPTY',
  LCD_SCREEN = 'LCD_SCREEN',
  LED_MATRIX = 'LED_MATRIX',
  NEO_PIXEL_STRIP = 'NEO_PIXEL_STRIP',
  MOTOR = 'MOTOR',
  PIN = 'PIN',
  ARDUINO = 'ARDUINO',
  BLUE_TOOTH = 'BLUE_TOOTH',
  LED_COLOR = 'LED_COLOR',
  RFID = 'RFID',
  BUTTON = 'BUTTON',
  MESSAGE = 'MESSAGE',
  TIME = 'TIME',
  IR_REMOTE = 'IR_REMOTE',
  ULTRASONICE_SENSOR = 'ULTRASONICE_SENSOR',
  TEMPERATURE_SENSOR = 'TEMPERATURE_SENSOR'
}
